default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
  username: <%= ENV['PORTFOLIO_DB_USER'] %>
  password: <%= ENV['PORTFOLIO-RAILS_DATABASE_PASSWORD'] %>
