default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  username: postgres
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
  username: <%= ENV['PSQL_USER_PRODUCTION'] %>
  password: <%= ENV['PSQL_PASSWORD_PRODUCTION'] %>
