default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DB_PORT_5432_DOCKER'] %>
  username: postgres
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
  username: <%= ENV['PORTFOLIO_DB_USER'] %>
  password: <%= ENV['PORTFOLIO_RAILS_DATABASE_PASSWORD'] %>
